"""Venue adapter protocol. The OMS talks only to this interface; every connector implements it."""
from __future__ import annotations

from typing import Protocol

from engine.execution.model import Fill, OrderRequest, Snapshot, VenueOrder


class VenueAdapter(Protocol):
    venue_id: str
    connector_type: str
    connector_version: str
    environment: str  # sim | testnet | demo | live
    paper: bool  # True only for the in-process simulated venue: nothing leaves the process
    supports_amend: bool

    def server_time_ms(self) -> int: ...
    def place(self, req: OrderRequest) -> VenueOrder: ...
    def amend(self, client_id: str, *, qty: float | None = None, stop_price: float | None = None) -> VenueOrder: ...
    def cancel(self, client_id: str) -> VenueOrder: ...
    def query(self, client_id: str) -> VenueOrder | None: ...
    def snapshot(self) -> Snapshot: ...
    def fills_since(self, seq: int) -> list[Fill]: ...
    def cancel_all_after(self, seconds: int) -> None: ...
